[package]
name = "pwplayer"
version = "0.1.0"
edition = "2021"

[dependencies]
bufstream = "0.1.4"
log = "0.4.22"
pipewire = "0.8.0"
pretty_env_logger = "0.5.0"
rand = "0.8.5"
symphonia = { version = "0.5.4", features = ["mp3", "flac"] }
